---

- name: register service with upstart
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: etc/init/zookeeper.conf.j2
      dest: /etc/init/zookeeper.conf
  when: ansible_distribution == 'Ubuntu'
  notify: restart zookeeper
  tags:
    - zookeeper

- name: register service with systemd
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: usr/lib/systemd/system/zookeeper.service.j2
      dest: /usr/lib/systemd/system/zookeeper.service
  when: ansible_distribution == 'CentOS'
  notify: restart zookeeper
  tags:
    - zookeeper

- name: register service with consul
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: etc/consul/zk-consul.json.j2
      dest: /etc/consul/zk-consul.json
  notify:
    - reload consul
  tags:
    - zookeeper

- name: drop zookeeper check script
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: usr/local/bin/zookeeper_check.sh
      dest: /usr/local/bin
  tags:
    - zookeeper

- meta: flush_handlers