---
- name: install nginx 
  yum: 
    name: nginx
    state: present
  tags:
    - common

- name: update nginx config
  sudo: yes
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - common
