---

- name: add webupd8 key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EEA14886

- name: add webupd8 repository
  apt_repository:
    repo: "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"
    state: present

- name: add mesosphere key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E56151BF

- name: add mesosphere repository
  apt_repository:
    repo: "deb http://repos.mesosphere.io/ubuntu trusty main"
    state: present