---
- name: add webupd8 key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EEA14886
  tags:
    - common

- name: add webupd8 repository
  apt_repository:
    repo: "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"
    state: present
  tags:
    - common

- name: add mesosphere key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E56151BF
  tags:
    - common

- name: add mesosphere repository
  apt_repository:
    repo: "deb http://repos.mesosphere.io/ubuntu trusty main"
    state: present
  tags:
    - common

- name: accept Oracle license
  debconf:
    name: "oracle-java7-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"
  tags:
    - common

- name: install common packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ common_packages }}"
    - "{{ common_deb_packages }}"
  tags:
    - common