---
- name: copy nginx configuration
  template:
    src: marathon.nginx.j2
    dest: /etc/marathon/marathon.nginx
  notify:
    - restart nginx-marathon
  tags:
    - marathon

- name: configure nginx
  command: curl -X PUT -d @/etc/marathon/marathon.nginx localhost:8500/v1/kv/service/nginx/templates/marathon
  tags:
    - marathon

- name: configure nginx-marathon
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-marathon.service.j2
      dest: /usr/lib/systemd/system/nginx-marathon.service
    - src: nginx-marathon.env.j2
      dest: /etc/default/nginx-marathon.env
  notify:
    - reload nginx-marathon
    - restart nginx-marathon
  tags:
    - marathon

- name: enable nginx-marathon
  service:
    name: nginx-marathon
    enabled: yes
    state: started
  notify:
    - restart nginx-marathon
  tags:
    - marathon
