---
- name: Install Oracle JDK 7
  hosts: tag_exhibitor_True
  sudo: True
  tasks:
    - name: accept Oracle license
      debconf: name=oracle-java7-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
    - name: add webupd8 apt key
      apt_key: keyserver=keyserver.ubuntu.com id=EEA14886
    - name: add webupd8 apt repo
      apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present
    - name: install java7
      apt: name=oracle-java7-installer update_cache=yes
