---
- name: Install Zookeeper
  hosts: tag_exhibitor_True
  sudo: True
  vars:
    install_dir: /opt/exhibitor
  tasks:
    - name: install zookeeper
      apt: name=zookeeper={{ zk_version }} state=present update_cache=yes
    - name: install git
      apt: name=git state=present
    - name: install maven
      apt: name=maven state=present
    - name: create exhibitor directory
      file: path=/opt/exhibitor state=directory owner=root group=root mode=0644
    - name: download maven pom file
      get_url: url=https://raw.githubusercontent.com/Netflix/exhibitor/master/exhibitor-standalone/src/main/resources/buildscripts/standalone/maven/pom.xml dest={{ install_dir }}
    - name: build exhibitor
      command: mvn clean package chdir={{ install_dir }} creates={{ install_dir }}/target/exhibitor-{{ exhibitor_version }}.jar
    #- name: 
#      notify:
#        - stop cassandra
#        - delete data directory
#+    - name: install pip
#+      apt: name=python-pip state=present update_cache=yes
#+    - name: install cassandra-driver
##+      pip: name=cassandra-driver
#+  handlers:
#+    - name: stop cassandra
#+      service: name=cassandra state=stopped
#+    - name: delete data directory
#+      file: path=/var/lib/cassandra/data state=absent