---
- name: Install Zookeeper
  hosts: tag_exhibitor_True
  sudo: True
  vars:
    zookeeper_upstart: templates/upstart/zookeeper.conf
    zookeeper_config: templates/zoo.cfg
    zookeeper_myid: templates/myid
    zookeeper_env: templates/environment
  tasks:
    - name: download zookeeper binary
      get_url: 
        url: "{{ zookeeper_mirror }}/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"
        dest: /opt
        sha256sum: "{{ zookeeper_sha256sum }}"

    - name: extract zookeeper binary
      command: tar xzf zookeeper-{{ zookeeper_version }}.tar.gz
      args:
        chdir: /opt
        creates: "/opt/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.jar"

    - name: create zookeeper upstart script
      template: 
        src: "{{ zookeeper_upstart }}"
        dest: "{{ upstart_dir }}/zookeeper.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart zookeeper service

    - name: create zookeeper environment file
      template:
        src: "{{ zookeeper_env }}"
        dest: "/opt/zookeeper-{{ zookeeper_version }}/conf/environment"
        owner: root
        group: root
        mode: 0644
      notify: restart zookeeper service

    - name: create zookeeper config
      template:
        src: "{{ zookeeper_config }}"
        dest: "/opt/zookeeper-{{ zookeeper_version }}/conf/zoo.cfg"
        owner: root 
        group: root 
        mode: 0644
      notify: restart zookeeper service

    - name: create zookeeper myid
      template:
        src: "{{ zookeeper_myid }}"
        dest: "/opt/zookeeper-{{ zookeeper_version }}/conf/myid"
        owner: root
        group: root
        mode: 0644
      notify: restart zookeeper service

  handlers:
    - name: restart zookeeper service
      service:
        name: zookeeper
        state: restarted