---
- name: Start the ec2 instances
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: create security group
    local_action:
      module: ec2_group
      name: basic-security-group
      description: "A basic security group"
      region: "{{ region }}"
      rules:
      - proto: tcp
        type: ssh
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 1024
        to_port: 65535
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        type: all
        cidr_ip: 0.0.0.0/0
    register: basic_sg
  - name: create instances
    local_action:
      module: ec2
      assign_public_ip: yes
      count_tag: exhibitor
      exact_count: "{{ exact_count }}"
      group_id: "{{ basic_sg.group_id }}"
      image: "{{ image }}"
      instance_tags:
        Name: "{{ name_tag }}"
        exhibitor: True
      instance_type: "{{ instance_type }}"
      key_name: "{{ key_name }}"
      region: "{{ region }}"
      #state: running
      volumes:
      - device_name: /dev/sda1
        volume_size: "{{ volume_size }}"
      wait: yes
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      zone: "{{ zone }}"
    register: ec2
  - name: wait for ssh to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=20 timeout=300 state=started
    with_items: ec2.instances
