---
kafka_mesos_mirror: https://kafka-mesos.s3.amazonaws.com
kafka_mesos_version: 0.9.0-beta
kafka_mirror: https://kafka-mesos.s3.amazonaws.com
kafka_version: 2.10-0.8.2.1

kafka_mesos_id: kafka-infrastructure
kafka_mesos_cpus: 0.5
kafka_mesos_mem: 256
kafka_mesos_storage: zk:/kafka-mesos
kafka_mesos_broker_logs: "{{ kafka_mesos_work_dir }}/logs"
kafka_mesos_api_port: 7000

kafka_mesos_framework_name: "kafka infrastructure"
kafka_mesos_framework_role: "infrastructure"

kafka_mesos_zk_dns: "zookeeper.service.{{ consul_dc }}"
kafka_mesos_zk_port: 2181
kafka_mesos_zk_connect: "zk://{{ kafka_mesos_zk_dns }}:{{ kafka_mesos_zk_port }}/mesos"

kafka_mesos_brokers: [0,1,2]
kafka_mesos_brokers_constraints: "hostname=like:*"
kafka_mesos_brokers_cpus: 2
kafka_mesos_brokers_heap: 1024
kafka_mesos_brokers_mem: 2048
kafka_mesos_brokers_options: host.name=0.0.0.0
