# Defines deployment design

- hosts: deployment
  sudo: True
  roles:
    - common
    - consul
    - consul-template
    - dnsmasq

- hosts: consul-servers

- hosts: zookeepers
  sudo: True
  roles:
    - zookeeper

- hosts: exhibitors
  sudo: True
  roles:
    - exhibitor

- hosts: mesos-slaves
  sudo: True
  roles:
    - mesos

- hosts: mesos-masters
  sudo: True
  roles:
    - mesos
    - marathon
    - kafka-mesos-marathon
    - kafka-manager-marathon

#- hosts: exhibitor
#  sudo: True
#  roles:
    #- zookeeper
    #- exhibitor
