# Defines vagrant deployment design

- hosts: all
  sudo: True
  roles:
    - common
    - dnsmasq
    - consul
    - consul-template
    - zookeeper
    - mesos
    - marathon
  vars:
     cluster: 'vagrant'
