---
- name: restart consul
  command: /usr/local/bin/consul-rolling-restart.sh
  notify:
    - wait for consul to listen

- name: reload consul
  command: service consul reload
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  command: consul-wait-for-leader.sh
