/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logline.proto

package proto;

public final class Logline {
  private Logline() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogLineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.LogLine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string line = 1;</code>
     */
    boolean hasLine();
    /**
     * <code>required string line = 1;</code>
     */
    java.lang.String getLine();
    /**
     * <code>required string line = 1;</code>
     */
    com.google.protobuf.ByteString
        getLineBytes();

    /**
     * <code>optional string source = 2 [default = ""];</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 2 [default = ""];</code>
     */
    java.lang.String getSource();
    /**
     * <code>optional string source = 2 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    java.util.List<proto.Logline.LogLine.Tag> 
        getTagList();
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    proto.Logline.LogLine.Tag getTag(int index);
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    int getTagCount();
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    java.util.List<? extends proto.Logline.LogLine.TagOrBuilder> 
        getTagOrBuilderList();
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    proto.Logline.LogLine.TagOrBuilder getTagOrBuilder(
        int index);

    /**
     * <code>optional int64 logtypeid = 4 [default = 0];</code>
     */
    boolean hasLogtypeid();
    /**
     * <code>optional int64 logtypeid = 4 [default = 0];</code>
     */
    long getLogtypeid();

    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    java.util.List<proto.Logline.LogLine.Timing> 
        getTimingsList();
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    proto.Logline.LogLine.Timing getTimings(int index);
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    int getTimingsCount();
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    java.util.List<? extends proto.Logline.LogLine.TimingOrBuilder> 
        getTimingsOrBuilderList();
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    proto.Logline.LogLine.TimingOrBuilder getTimingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.LogLine}
   */
  public static final class LogLine extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.LogLine)
      LogLineOrBuilder {
    // Use LogLine.newBuilder() to construct.
    private LogLine(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogLine(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogLine defaultInstance;
    public static LogLine getDefaultInstance() {
      return defaultInstance;
    }

    public LogLine getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogLine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              line_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              source_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                tag_ = new java.util.ArrayList<proto.Logline.LogLine.Tag>();
                mutable_bitField0_ |= 0x00000004;
              }
              tag_.add(input.readMessage(proto.Logline.LogLine.Tag.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              logtypeid_ = input.readInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                timings_ = new java.util.ArrayList<proto.Logline.LogLine.Timing>();
                mutable_bitField0_ |= 0x00000010;
              }
              timings_.add(input.readMessage(proto.Logline.LogLine.Timing.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          tag_ = java.util.Collections.unmodifiableList(tag_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          timings_ = java.util.Collections.unmodifiableList(timings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Logline.internal_static_proto_LogLine_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Logline.internal_static_proto_LogLine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Logline.LogLine.class, proto.Logline.LogLine.Builder.class);
    }

    public static com.google.protobuf.Parser<LogLine> PARSER =
        new com.google.protobuf.AbstractParser<LogLine>() {
      public LogLine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogLine(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogLine> getParserForType() {
      return PARSER;
    }

    public interface TagOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.LogLine.Tag)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>required string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>required string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code proto.LogLine.Tag}
     */
    public static final class Tag extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:proto.LogLine.Tag)
        TagOrBuilder {
      // Use Tag.newBuilder() to construct.
      private Tag(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Tag(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Tag defaultInstance;
      public static Tag getDefaultInstance() {
        return defaultInstance;
      }

      public Tag getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Tag(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                key_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                value_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Logline.internal_static_proto_LogLine_Tag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Logline.internal_static_proto_LogLine_Tag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Logline.LogLine.Tag.class, proto.Logline.LogLine.Tag.Builder.class);
      }

      public static com.google.protobuf.Parser<Tag> PARSER =
          new com.google.protobuf.AbstractParser<Tag>() {
        public Tag parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Tag(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Tag> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static proto.Logline.LogLine.Tag parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.Logline.LogLine.Tag parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.Logline.LogLine.Tag parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.Logline.LogLine.Tag parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.Logline.LogLine.Tag parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.Logline.LogLine.Tag parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static proto.Logline.LogLine.Tag parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static proto.Logline.LogLine.Tag parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static proto.Logline.LogLine.Tag parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.Logline.LogLine.Tag parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(proto.Logline.LogLine.Tag prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.LogLine.Tag}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.LogLine.Tag)
          proto.Logline.LogLine.TagOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.Logline.internal_static_proto_LogLine_Tag_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.Logline.internal_static_proto_LogLine_Tag_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  proto.Logline.LogLine.Tag.class, proto.Logline.LogLine.Tag.Builder.class);
        }

        // Construct using proto.Logline.LogLine.Tag.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.Logline.internal_static_proto_LogLine_Tag_descriptor;
        }

        public proto.Logline.LogLine.Tag getDefaultInstanceForType() {
          return proto.Logline.LogLine.Tag.getDefaultInstance();
        }

        public proto.Logline.LogLine.Tag build() {
          proto.Logline.LogLine.Tag result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public proto.Logline.LogLine.Tag buildPartial() {
          proto.Logline.LogLine.Tag result = new proto.Logline.LogLine.Tag(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.Logline.LogLine.Tag) {
            return mergeFrom((proto.Logline.LogLine.Tag)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(proto.Logline.LogLine.Tag other) {
          if (other == proto.Logline.LogLine.Tag.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          proto.Logline.LogLine.Tag parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (proto.Logline.LogLine.Tag) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              value_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:proto.LogLine.Tag)
      }

      static {
        defaultInstance = new Tag(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:proto.LogLine.Tag)
    }

    public interface TimingOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.LogLine.Timing)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string eventName = 1;</code>
       */
      boolean hasEventName();
      /**
       * <code>required string eventName = 1;</code>
       */
      java.lang.String getEventName();
      /**
       * <code>required string eventName = 1;</code>
       */
      com.google.protobuf.ByteString
          getEventNameBytes();

      /**
       * <code>required int64 value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required int64 value = 2;</code>
       */
      long getValue();
    }
    /**
     * Protobuf type {@code proto.LogLine.Timing}
     */
    public static final class Timing extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:proto.LogLine.Timing)
        TimingOrBuilder {
      // Use Timing.newBuilder() to construct.
      private Timing(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Timing(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Timing defaultInstance;
      public static Timing getDefaultInstance() {
        return defaultInstance;
      }

      public Timing getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Timing(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                eventName_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                value_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Logline.internal_static_proto_LogLine_Timing_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Logline.internal_static_proto_LogLine_Timing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Logline.LogLine.Timing.class, proto.Logline.LogLine.Timing.Builder.class);
      }

      public static com.google.protobuf.Parser<Timing> PARSER =
          new com.google.protobuf.AbstractParser<Timing>() {
        public Timing parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Timing(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Timing> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int EVENTNAME_FIELD_NUMBER = 1;
      private java.lang.Object eventName_;
      /**
       * <code>required string eventName = 1;</code>
       */
      public boolean hasEventName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string eventName = 1;</code>
       */
      public java.lang.String getEventName() {
        java.lang.Object ref = eventName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            eventName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string eventName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEventNameBytes() {
        java.lang.Object ref = eventName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private long value_;
      /**
       * <code>required int64 value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 value = 2;</code>
       */
      public long getValue() {
        return value_;
      }

      private void initFields() {
        eventName_ = "";
        value_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasEventName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getEventNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, value_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getEventNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static proto.Logline.LogLine.Timing parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.Logline.LogLine.Timing parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.Logline.LogLine.Timing parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.Logline.LogLine.Timing parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.Logline.LogLine.Timing parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.Logline.LogLine.Timing parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static proto.Logline.LogLine.Timing parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static proto.Logline.LogLine.Timing parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static proto.Logline.LogLine.Timing parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.Logline.LogLine.Timing parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(proto.Logline.LogLine.Timing prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.LogLine.Timing}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.LogLine.Timing)
          proto.Logline.LogLine.TimingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.Logline.internal_static_proto_LogLine_Timing_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.Logline.internal_static_proto_LogLine_Timing_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  proto.Logline.LogLine.Timing.class, proto.Logline.LogLine.Timing.Builder.class);
        }

        // Construct using proto.Logline.LogLine.Timing.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          eventName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.Logline.internal_static_proto_LogLine_Timing_descriptor;
        }

        public proto.Logline.LogLine.Timing getDefaultInstanceForType() {
          return proto.Logline.LogLine.Timing.getDefaultInstance();
        }

        public proto.Logline.LogLine.Timing build() {
          proto.Logline.LogLine.Timing result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public proto.Logline.LogLine.Timing buildPartial() {
          proto.Logline.LogLine.Timing result = new proto.Logline.LogLine.Timing(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.eventName_ = eventName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.Logline.LogLine.Timing) {
            return mergeFrom((proto.Logline.LogLine.Timing)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(proto.Logline.LogLine.Timing other) {
          if (other == proto.Logline.LogLine.Timing.getDefaultInstance()) return this;
          if (other.hasEventName()) {
            bitField0_ |= 0x00000001;
            eventName_ = other.eventName_;
            onChanged();
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasEventName()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          proto.Logline.LogLine.Timing parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (proto.Logline.LogLine.Timing) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object eventName_ = "";
        /**
         * <code>required string eventName = 1;</code>
         */
        public boolean hasEventName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string eventName = 1;</code>
         */
        public java.lang.String getEventName() {
          java.lang.Object ref = eventName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              eventName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string eventName = 1;</code>
         */
        public com.google.protobuf.ByteString
            getEventNameBytes() {
          java.lang.Object ref = eventName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            eventName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string eventName = 1;</code>
         */
        public Builder setEventName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          eventName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string eventName = 1;</code>
         */
        public Builder clearEventName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          eventName_ = getDefaultInstance().getEventName();
          onChanged();
          return this;
        }
        /**
         * <code>required string eventName = 1;</code>
         */
        public Builder setEventNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          eventName_ = value;
          onChanged();
          return this;
        }

        private long value_ ;
        /**
         * <code>required int64 value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 value = 2;</code>
         */
        public long getValue() {
          return value_;
        }
        /**
         * <code>required int64 value = 2;</code>
         */
        public Builder setValue(long value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:proto.LogLine.Timing)
      }

      static {
        defaultInstance = new Timing(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:proto.LogLine.Timing)
    }

    private int bitField0_;
    public static final int LINE_FIELD_NUMBER = 1;
    private java.lang.Object line_;
    /**
     * <code>required string line = 1;</code>
     */
    public boolean hasLine() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string line = 1;</code>
     */
    public java.lang.String getLine() {
      java.lang.Object ref = line_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          line_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string line = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLineBytes() {
      java.lang.Object ref = line_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        line_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 2;
    private java.lang.Object source_;
    /**
     * <code>optional string source = 2 [default = ""];</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string source = 2 [default = ""];</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 2 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_FIELD_NUMBER = 3;
    private java.util.List<proto.Logline.LogLine.Tag> tag_;
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    public java.util.List<proto.Logline.LogLine.Tag> getTagList() {
      return tag_;
    }
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    public java.util.List<? extends proto.Logline.LogLine.TagOrBuilder> 
        getTagOrBuilderList() {
      return tag_;
    }
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    public proto.Logline.LogLine.Tag getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated .proto.LogLine.Tag tag = 3;</code>
     */
    public proto.Logline.LogLine.TagOrBuilder getTagOrBuilder(
        int index) {
      return tag_.get(index);
    }

    public static final int LOGTYPEID_FIELD_NUMBER = 4;
    private long logtypeid_;
    /**
     * <code>optional int64 logtypeid = 4 [default = 0];</code>
     */
    public boolean hasLogtypeid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 logtypeid = 4 [default = 0];</code>
     */
    public long getLogtypeid() {
      return logtypeid_;
    }

    public static final int TIMINGS_FIELD_NUMBER = 5;
    private java.util.List<proto.Logline.LogLine.Timing> timings_;
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    public java.util.List<proto.Logline.LogLine.Timing> getTimingsList() {
      return timings_;
    }
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    public java.util.List<? extends proto.Logline.LogLine.TimingOrBuilder> 
        getTimingsOrBuilderList() {
      return timings_;
    }
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    public int getTimingsCount() {
      return timings_.size();
    }
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    public proto.Logline.LogLine.Timing getTimings(int index) {
      return timings_.get(index);
    }
    /**
     * <code>repeated .proto.LogLine.Timing timings = 5;</code>
     */
    public proto.Logline.LogLine.TimingOrBuilder getTimingsOrBuilder(
        int index) {
      return timings_.get(index);
    }

    private void initFields() {
      line_ = "";
      source_ = "";
      tag_ = java.util.Collections.emptyList();
      logtypeid_ = 0L;
      timings_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLine()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTagCount(); i++) {
        if (!getTag(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getTimingsCount(); i++) {
        if (!getTimings(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLineBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSourceBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        output.writeMessage(3, tag_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, logtypeid_);
      }
      for (int i = 0; i < timings_.size(); i++) {
        output.writeMessage(5, timings_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLineBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSourceBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, tag_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, logtypeid_);
      }
      for (int i = 0; i < timings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, timings_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.Logline.LogLine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Logline.LogLine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Logline.LogLine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Logline.LogLine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Logline.LogLine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Logline.LogLine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.Logline.LogLine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.Logline.LogLine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.Logline.LogLine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Logline.LogLine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.Logline.LogLine prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.LogLine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.LogLine)
        proto.Logline.LogLineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Logline.internal_static_proto_LogLine_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Logline.internal_static_proto_LogLine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Logline.LogLine.class, proto.Logline.LogLine.Builder.class);
      }

      // Construct using proto.Logline.LogLine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTagFieldBuilder();
          getTimingsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        line_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          tagBuilder_.clear();
        }
        logtypeid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (timingsBuilder_ == null) {
          timings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          timingsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Logline.internal_static_proto_LogLine_descriptor;
      }

      public proto.Logline.LogLine getDefaultInstanceForType() {
        return proto.Logline.LogLine.getDefaultInstance();
      }

      public proto.Logline.LogLine build() {
        proto.Logline.LogLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Logline.LogLine buildPartial() {
        proto.Logline.LogLine result = new proto.Logline.LogLine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.line_ = line_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.source_ = source_;
        if (tagBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            tag_ = java.util.Collections.unmodifiableList(tag_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.logtypeid_ = logtypeid_;
        if (timingsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            timings_ = java.util.Collections.unmodifiableList(timings_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.timings_ = timings_;
        } else {
          result.timings_ = timingsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Logline.LogLine) {
          return mergeFrom((proto.Logline.LogLine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Logline.LogLine other) {
        if (other == proto.Logline.LogLine.getDefaultInstance()) return this;
        if (other.hasLine()) {
          bitField0_ |= 0x00000001;
          line_ = other.line_;
          onChanged();
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000002;
          source_ = other.source_;
          onChanged();
        }
        if (tagBuilder_ == null) {
          if (!other.tag_.isEmpty()) {
            if (tag_.isEmpty()) {
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTagIsMutable();
              tag_.addAll(other.tag_);
            }
            onChanged();
          }
        } else {
          if (!other.tag_.isEmpty()) {
            if (tagBuilder_.isEmpty()) {
              tagBuilder_.dispose();
              tagBuilder_ = null;
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000004);
              tagBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagFieldBuilder() : null;
            } else {
              tagBuilder_.addAllMessages(other.tag_);
            }
          }
        }
        if (other.hasLogtypeid()) {
          setLogtypeid(other.getLogtypeid());
        }
        if (timingsBuilder_ == null) {
          if (!other.timings_.isEmpty()) {
            if (timings_.isEmpty()) {
              timings_ = other.timings_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureTimingsIsMutable();
              timings_.addAll(other.timings_);
            }
            onChanged();
          }
        } else {
          if (!other.timings_.isEmpty()) {
            if (timingsBuilder_.isEmpty()) {
              timingsBuilder_.dispose();
              timingsBuilder_ = null;
              timings_ = other.timings_;
              bitField0_ = (bitField0_ & ~0x00000010);
              timingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimingsFieldBuilder() : null;
            } else {
              timingsBuilder_.addAllMessages(other.timings_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLine()) {
          
          return false;
        }
        for (int i = 0; i < getTagCount(); i++) {
          if (!getTag(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getTimingsCount(); i++) {
          if (!getTimings(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Logline.LogLine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Logline.LogLine) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object line_ = "";
      /**
       * <code>required string line = 1;</code>
       */
      public boolean hasLine() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string line = 1;</code>
       */
      public java.lang.String getLine() {
        java.lang.Object ref = line_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            line_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string line = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLineBytes() {
        java.lang.Object ref = line_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          line_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string line = 1;</code>
       */
      public Builder setLine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string line = 1;</code>
       */
      public Builder clearLine() {
        bitField0_ = (bitField0_ & ~0x00000001);
        line_ = getDefaultInstance().getLine();
        onChanged();
        return this;
      }
      /**
       * <code>required string line = 1;</code>
       */
      public Builder setLineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        line_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>optional string source = 2 [default = ""];</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }

      private java.util.List<proto.Logline.LogLine.Tag> tag_ =
        java.util.Collections.emptyList();
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          tag_ = new java.util.ArrayList<proto.Logline.LogLine.Tag>(tag_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Logline.LogLine.Tag, proto.Logline.LogLine.Tag.Builder, proto.Logline.LogLine.TagOrBuilder> tagBuilder_;

      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public java.util.List<proto.Logline.LogLine.Tag> getTagList() {
        if (tagBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tag_);
        } else {
          return tagBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public int getTagCount() {
        if (tagBuilder_ == null) {
          return tag_.size();
        } else {
          return tagBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public proto.Logline.LogLine.Tag getTag(int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);
        } else {
          return tagBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder setTag(
          int index, proto.Logline.LogLine.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.set(index, value);
          onChanged();
        } else {
          tagBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder setTag(
          int index, proto.Logline.LogLine.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder addTag(proto.Logline.LogLine.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(value);
          onChanged();
        } else {
          tagBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder addTag(
          int index, proto.Logline.LogLine.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(index, value);
          onChanged();
        } else {
          tagBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder addTag(
          proto.Logline.LogLine.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder addTag(
          int index, proto.Logline.LogLine.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder addAllTag(
          java.lang.Iterable<? extends proto.Logline.LogLine.Tag> values) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tag_);
          onChanged();
        } else {
          tagBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          tagBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public Builder removeTag(int index) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.remove(index);
          onChanged();
        } else {
          tagBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public proto.Logline.LogLine.Tag.Builder getTagBuilder(
          int index) {
        return getTagFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public proto.Logline.LogLine.TagOrBuilder getTagOrBuilder(
          int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);  } else {
          return tagBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public java.util.List<? extends proto.Logline.LogLine.TagOrBuilder> 
           getTagOrBuilderList() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tag_);
        }
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public proto.Logline.LogLine.Tag.Builder addTagBuilder() {
        return getTagFieldBuilder().addBuilder(
            proto.Logline.LogLine.Tag.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public proto.Logline.LogLine.Tag.Builder addTagBuilder(
          int index) {
        return getTagFieldBuilder().addBuilder(
            index, proto.Logline.LogLine.Tag.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.LogLine.Tag tag = 3;</code>
       */
      public java.util.List<proto.Logline.LogLine.Tag.Builder> 
           getTagBuilderList() {
        return getTagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Logline.LogLine.Tag, proto.Logline.LogLine.Tag.Builder, proto.Logline.LogLine.TagOrBuilder> 
          getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.Logline.LogLine.Tag, proto.Logline.LogLine.Tag.Builder, proto.Logline.LogLine.TagOrBuilder>(
                  tag_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }

      private long logtypeid_ ;
      /**
       * <code>optional int64 logtypeid = 4 [default = 0];</code>
       */
      public boolean hasLogtypeid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 logtypeid = 4 [default = 0];</code>
       */
      public long getLogtypeid() {
        return logtypeid_;
      }
      /**
       * <code>optional int64 logtypeid = 4 [default = 0];</code>
       */
      public Builder setLogtypeid(long value) {
        bitField0_ |= 0x00000008;
        logtypeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 logtypeid = 4 [default = 0];</code>
       */
      public Builder clearLogtypeid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        logtypeid_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<proto.Logline.LogLine.Timing> timings_ =
        java.util.Collections.emptyList();
      private void ensureTimingsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          timings_ = new java.util.ArrayList<proto.Logline.LogLine.Timing>(timings_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Logline.LogLine.Timing, proto.Logline.LogLine.Timing.Builder, proto.Logline.LogLine.TimingOrBuilder> timingsBuilder_;

      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public java.util.List<proto.Logline.LogLine.Timing> getTimingsList() {
        if (timingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(timings_);
        } else {
          return timingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public int getTimingsCount() {
        if (timingsBuilder_ == null) {
          return timings_.size();
        } else {
          return timingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public proto.Logline.LogLine.Timing getTimings(int index) {
        if (timingsBuilder_ == null) {
          return timings_.get(index);
        } else {
          return timingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder setTimings(
          int index, proto.Logline.LogLine.Timing value) {
        if (timingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimingsIsMutable();
          timings_.set(index, value);
          onChanged();
        } else {
          timingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder setTimings(
          int index, proto.Logline.LogLine.Timing.Builder builderForValue) {
        if (timingsBuilder_ == null) {
          ensureTimingsIsMutable();
          timings_.set(index, builderForValue.build());
          onChanged();
        } else {
          timingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder addTimings(proto.Logline.LogLine.Timing value) {
        if (timingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimingsIsMutable();
          timings_.add(value);
          onChanged();
        } else {
          timingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder addTimings(
          int index, proto.Logline.LogLine.Timing value) {
        if (timingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimingsIsMutable();
          timings_.add(index, value);
          onChanged();
        } else {
          timingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder addTimings(
          proto.Logline.LogLine.Timing.Builder builderForValue) {
        if (timingsBuilder_ == null) {
          ensureTimingsIsMutable();
          timings_.add(builderForValue.build());
          onChanged();
        } else {
          timingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder addTimings(
          int index, proto.Logline.LogLine.Timing.Builder builderForValue) {
        if (timingsBuilder_ == null) {
          ensureTimingsIsMutable();
          timings_.add(index, builderForValue.build());
          onChanged();
        } else {
          timingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder addAllTimings(
          java.lang.Iterable<? extends proto.Logline.LogLine.Timing> values) {
        if (timingsBuilder_ == null) {
          ensureTimingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, timings_);
          onChanged();
        } else {
          timingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder clearTimings() {
        if (timingsBuilder_ == null) {
          timings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          timingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public Builder removeTimings(int index) {
        if (timingsBuilder_ == null) {
          ensureTimingsIsMutable();
          timings_.remove(index);
          onChanged();
        } else {
          timingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public proto.Logline.LogLine.Timing.Builder getTimingsBuilder(
          int index) {
        return getTimingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public proto.Logline.LogLine.TimingOrBuilder getTimingsOrBuilder(
          int index) {
        if (timingsBuilder_ == null) {
          return timings_.get(index);  } else {
          return timingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public java.util.List<? extends proto.Logline.LogLine.TimingOrBuilder> 
           getTimingsOrBuilderList() {
        if (timingsBuilder_ != null) {
          return timingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(timings_);
        }
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public proto.Logline.LogLine.Timing.Builder addTimingsBuilder() {
        return getTimingsFieldBuilder().addBuilder(
            proto.Logline.LogLine.Timing.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public proto.Logline.LogLine.Timing.Builder addTimingsBuilder(
          int index) {
        return getTimingsFieldBuilder().addBuilder(
            index, proto.Logline.LogLine.Timing.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.LogLine.Timing timings = 5;</code>
       */
      public java.util.List<proto.Logline.LogLine.Timing.Builder> 
           getTimingsBuilderList() {
        return getTimingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Logline.LogLine.Timing, proto.Logline.LogLine.Timing.Builder, proto.Logline.LogLine.TimingOrBuilder> 
          getTimingsFieldBuilder() {
        if (timingsBuilder_ == null) {
          timingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.Logline.LogLine.Timing, proto.Logline.LogLine.Timing.Builder, proto.Logline.LogLine.TimingOrBuilder>(
                  timings_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          timings_ = null;
        }
        return timingsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.LogLine)
    }

    static {
      defaultInstance = new LogLine(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.LogLine)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LogLine_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LogLine_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LogLine_Tag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LogLine_Tag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LogLine_Timing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LogLine_Timing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlogline.proto\022\005proto\"\327\001\n\007LogLine\022\014\n\004li" +
      "ne\030\001 \002(\t\022\020\n\006source\030\002 \001(\t:\000\022\037\n\003tag\030\003 \003(\0132" +
      "\022.proto.LogLine.Tag\022\024\n\tlogtypeid\030\004 \001(\003:\001" +
      "0\022&\n\007timings\030\005 \003(\0132\025.proto.LogLine.Timin" +
      "g\032!\n\003Tag\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\032*\n\006" +
      "Timing\022\021\n\teventName\030\001 \002(\t\022\r\n\005value\030\002 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_LogLine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_LogLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_LogLine_descriptor,
        new java.lang.String[] { "Line", "Source", "Tag", "Logtypeid", "Timings", });
    internal_static_proto_LogLine_Tag_descriptor =
      internal_static_proto_LogLine_descriptor.getNestedTypes().get(0);
    internal_static_proto_LogLine_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_LogLine_Tag_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_LogLine_Timing_descriptor =
      internal_static_proto_LogLine_descriptor.getNestedTypes().get(1);
    internal_static_proto_LogLine_Timing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_LogLine_Timing_descriptor,
        new java.lang.String[] { "EventName", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
