---
- name: reload marathon
  command: systemctl daemon-reload
  notify:
    - wait for marathon to listen

- name: restart marathon 
  command: systemctl restart marathon
  notify:
    - wait for marathon to listen

- name: wait for marathon to listen
  command: /usr/local/bin/marathon-wait-for-listen.sh

- name: reload consul
  command: "{{ consul_bin }} reload"

- name: restart nginx-marathon
  command: systemctl restart nginx-marathon

- name: reload nginx-marathon
  command: systemctl daemon-reload
