---

- name: create common configuration on master
  template:
    src: etc/default/mesos.j2
    dest: /etc/default/mesos
  notify: 
    - restart mesos-master
  tags:
    - mesos

- name: create master configuration
  template:
    src: etc/default/mesos-master.j2
    dest: /etc/default/mesos-master
  notify: restart mesos-master
  tags:
    - mesos

- name: create master config dir
  file:
    path: /etc/mesos-master
    state: directory
  tags:
    - mesos

- name: set master flags
  template:
    src: "etc/mesos-master/{{ item }}"
    dest: "/etc/mesos-master/{{ item }}"
  with_items:
    - recovery_slave_removal_limit
    - "{{ mesos_log_auto_initialize }}"
  notify: restart mesos-master
  tags:
    - mesos

- name: create replicated log dir
  file:
    path: "{{ mesos_replicated_log_dir }}"
    state: directory
  tags:
    - mesos

- name: check if log is initialized
  shell: "[ -f {{ mesos_replicated_log_dir }}/LOG ]"
  ignore_errors: true
  register: repl_log_state
  tags:
    - mesos

- name: initialize log
  shell: "mesos-log initialize --path={{ mesos_replicated_log_dir }}"
  when: repl_log_state|failed
  notify: restart mesos-master
  tags:
    - mesos
